module:
  hugoVersion:
    min: "0.84.0"

params:
  ananke_socials:
  - name: twitter
    url: https://twitter.com/cyb3rshi3ld
  - name: linkedin
    url: https://www.linkedin.com/company/cybershieldacademy/
    