baseURL = "https://cybersecurityos.net"
languageCode = "en-us"
title = "CybersecurityOS"
theme = "ananke"

# SEO Metadata
description = "A comprehensive resource for cybersecurity professionals, providing insights, tools, and services."
keywords = "cybersecurity, security tools, professional development, best practices"
author = "Your Name"  # Replace with your actual name or organization
googleAnalytics = "YOUR_TRACKING_ID"  # Replace with your Google Analytics tracking ID

# Permalinks
[permalinks]
  post = "/blog/:year/:month/:day/:slug/"  # Customize the permalink structure for blog posts

# Taxonomies: add social taxonomy to address deprecation of .Site.Social
[taxonomies]
  tag = "tags"
  category = "categories"
  social = "social"

# Params (Optional: Adjust as needed based on your theme)
[params]
  favicon = "images/c-os-l.svg"   # Path to your favicon
  site_logo = "images/c-os.svg" 
  showSocialLinks = true        # Show social links in the footer (if supported by the theme)
  paginate = 10                  # this is set low for demonstrating with dummy content. Set to a higher number
  rss = "index.xml" #rss
  show_reading_time = true

[params.social]
  linkedin = "https://www.linkedin.com/company/cybershieldacademy/" #linkedin
  twitter = 'cyb3rshi3ld'
  
# Menu Configuration (Optional: Customize navigation)
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Store"
  url = "https://store.cybersecurityos.net/"
  weight = 4

 [[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5

# Enable the sitemap
[params.sitemap]
  sitemap = true

[services]
  [services.disqus]
    shortname = 'https-www-cybersecurityos-net'