baseURL = "https://cybersecurityos.net"
languageCode = "en-us"
title = "CybersecurityOS"
theme = "ananke"

# SEO Metadata
description = "A comprehensive resource for cybersecurity professionals, providing insights, tools, and services."
keywords = "cybersecurity, security tools, professional development, best practices"
author = "Your Name"  # Replace with your actual name or organization
googleAnalytics = "YOUR_TRACKING_ID"  # Replace with your Google Analytics tracking ID

# Permalinks
[permalinks]
  post = "/blog/:year/:month/:day/:slug/"  # Customize the permalink structure for blog posts

# Params (Optional: Adjust as needed based on your theme)
[params]
  favicon = "img/favicon.ico"  # Path to your favicon
  logo = "img/logo.png"         # Path to your logo
  showSocialLinks = true        # Show social links in the footer (if supported by the theme)
  disqusShortname = "your-disqus-shortname"  # If you are using Disqus for comments

# Menu Configuration (Optional: Customize navigation)
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

# Enable the sitemap
[params.sitemap]
  sitemap = true

