name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run markdownlint
        run: npm run lint:md
        # Allow markdown lint failures without failing the entire workflow
        continue-on-error: true

  hugo-build:
    name: Hugo Build
    runs-on: ubuntu-latest
    needs: markdown-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Build site with Hugo
        run: hugo --minify