name: Lint Markdown Files

on:
  push:
    branches:
      - master  # Change to your default branch
  pull_request:
    branches:
      - master  # Change to your default branch

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: markdownlint content/**/*.md  # This will target all .md files in the content folder and its subfolders
